In [ ]:
import numpy as np
import tensorflow as tf
import sys

In [ ]:
tf.__version__

'2.9.2'

In [ ]:
!python --version

Python 3.7.15


# Indexing 

- starts at zero 
- (-)ve indices count backwards from the end
- colons ":" are used for slice:start:stop:step


In [ ]:
rank1_tensor = tf.constant([11, 22, 33, 44, 55, 66, 77, 88, 99])
rank1_tensor


<tf.Tensor: shape=(9,), dtype=int32, numpy=array([11, 22, 33, 44, 55, 66, 77, 88, 99], dtype=int32)>

In [ ]:
#get just number by using .numpy()
rank1_tensor[0].numpy()

11

In [ ]:
# -1 is last entry, counting backwards
rank1_tensor[-8]

<tf.Tensor: shape=(), dtype=int32, numpy=22>

In [ ]:
#no need to type 0 if you start at index[0]
rank1_tensor[:5]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([11, 22, 33, 44, 55], dtype=int32)>

In [ ]:
#if you start in th middle type start and stop index
rank1_tensor[3:5]

array([44, 55], dtype=int32)

In [ ]:
#get reverse tensor
rank1_tensor[::-1].numpy()

array([99, 88, 77, 66, 55, 44, 33, 22, 11], dtype=int32)

Multi-axes indexing

In [ ]:
rank2_tensor = tf.constant([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]])
rank2_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
# x[row_start:row_end, col_start:col_end]
rank2_tensor[1, 1]

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [ ]:
#x[row_start:row_end+1, col_start:col_end+1]
rank2_tensor[0:2, 0:2]

#same as

rank2_tensor[:2, :2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

In [ ]:
# just ":" means all entries, -1 is last row
rank2_tensor[-1, :].numpy()

array([7, 8, 9], dtype=int32)

In [ ]:
rank2_tensor[:, -1].numpy()

array([3, 6, 9], dtype=int32)

In [ ]:
rank2_tensor[-2, -1]

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [ ]:
  # ends at the end
  rank2_tensor[1:, 1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [8, 9]], dtype=int32)>

Rank3 Tensor

In [ ]:
rank3_tensor = tf.constant([
                            [[1, 2, 3, 4],
                             [4, 5, 6, 4]],
                            
                            [[10, 20, 30, 5],
                             [40, 50, 60, 5]],
                            
                            [[11, 22, 33, 6],
                             [44, 55, 66, 6]]
                            ])
rank3_tensor
#shape = stacks, row/stack, column/stack

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  4]],

       [[10, 20, 30,  5],
        [40, 50, 60,  5]],

       [[11, 22, 33,  6],
        [44, 55, 66,  6]]], dtype=int32)>

In [ ]:
rank3_tensor[:, :, 0]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  4],
       [10, 40],
       [11, 44]], dtype=int32)>

In [ ]:
rank3_tensor[:2, :, 1:3]

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 2,  3],
        [ 5,  6]],

       [[20, 30],
        [50, 60]]], dtype=int32)>